@echo off
setlocal

set "SCRIPT_DIR=%~dp0"
set "REPO_ROOT=%SCRIPT_DIR%.."
for %%I in ("%REPO_ROOT%") do set "REPO_ROOT=%%~fI"

set "ROM_INIT_HEX_OVERRIDE=%REPO_ROOT%\build\sw\YH_rv_cpu_uart_alive.hex"
set "ROM_INIT_MEM32_HEX_OVERRIDE=%REPO_ROOT%\build\sw\YH_rv_cpu_uart_alive.mem32.hex"
set "ROM_BYTES_OVERRIDE=8192"
set "RAM_BYTES_OVERRIDE=16384"
set "PYNQ_INPUT_CLOCK_PERIOD_NS_OVERRIDE=8.000"
set "PYNQ_CPU_CLK_FREQ_HZ_OVERRIDE=50000000"
set "PYNQ_USE_CLK_MMCM_62M5_OVERRIDE=0"
set "PYNQ_USE_CLK_MMCM_50M_OVERRIDE=1"
set "PYNQ_ENABLE_M_EXTENSION_OVERRIDE=0"
set "PYNQ_ENABLE_ZMMUL_EXTENSION_OVERRIDE=1"
set "PYNQ_ENABLE_BITMANIP_EXTENSION_OVERRIDE=1"
set "PYNQ_ENABLE_ZBC_EXTENSION_OVERRIDE=0"
set "PYNQ_ENABLE_ZICOND_EXTENSION_OVERRIDE=0"
set "PYNQ_ENABLE_ZBKB_EXTENSION_OVERRIDE=0"
set "PYNQ_ENABLE_XTHEAD_EXTENSION_OVERRIDE=0"
set "PYNQ_ENABLE_XTHEAD_COND_MOVE_OVERRIDE=0"
set "PYNQ_ENABLE_ID_BRANCH_EX_FORWARD_OVERRIDE=0"
set "PYNQ_DEBUG_LED_MODE_OVERRIDE=1"
set "PYNQ_DEBUG_UART_DIAG_MODE_OVERRIDE=1"

call "%SCRIPT_DIR%build_pynq_z2_project.bat" impl
exit /b %ERRORLEVEL%
