@echo off
setlocal EnableDelayedExpansion

for %%I in ("%~dp0..") do set PROJECT_DIR=%%~fI
set TARGET=%~1
set DHRYSTONE_RUNS=%~2
set CLOCK_HZ=%~3
set MAX_CYCLES=%~4
set SUMMARY_FILE=%~5

if "%TARGET%"=="" set TARGET=rv32i_zmmul_zba_zbb_zbs_zbc_zicond_xthead_mac_idbr
if "%DHRYSTONE_RUNS%"=="" set DHRYSTONE_RUNS=10
if "%CLOCK_HZ%"=="" set CLOCK_HZ=100000000UL
if "%MAX_CYCLES%"=="" set MAX_CYCLES=250000000
if "%SUMMARY_FILE%"=="" set SUMMARY_FILE=%PROJECT_DIR%\build\sw\YH_rv_cpu_dhrystone_fpga.summary.txt

for %%I in ("%SUMMARY_FILE%") do (
    set SUMMARY_FILE=%%~fI
    set OUTPUT_DIR=%%~dpI
    set OUTPUT_STEM=%%~nI
)
if /I "!OUTPUT_STEM:~-8!"==".summary" set OUTPUT_STEM=!OUTPUT_STEM:~0,-8!
if not exist "!OUTPUT_DIR!" mkdir "!OUTPUT_DIR!"
set LOG_FILE=!OUTPUT_DIR!!OUTPUT_STEM!.log

set OUTPUT_NAME=YH_rv_cpu_dhrystone_fpga
set TEST_TOP=YH_rv_cpu_dhrystone_tb
set ENABLE_M_EXTENSION=1
set ENABLE_ZMMUL_EXTENSION=0
set ENABLE_BITMANIP_EXTENSION=1
set ENABLE_ZBC_EXTENSION=0
set ENABLE_ZICOND_EXTENSION=0
set ENABLE_ZBKB_EXTENSION=0
set ENABLE_XTHEAD_EXTENSION=0
set ENABLE_XTHEAD_CRC_EXTENSION=1
set ENABLE_XTHEAD_MUL_EXTENSION=1
set ENABLE_XTHEAD_COND_MOVE=0
set ENABLE_XTHEAD_ADDSL_EXTENSION=0
set ENABLE_XTHEAD_MEMPAIR_EXTENSION=1
set ENABLE_XTHEAD_BASE_UPDATE_EXTENSION=1
set ENABLE_ID_BRANCH_EX_FORWARD=1
set ENABLE_ID_BRANCH_EXMEM_LOAD_FORWARD=1
set ENABLE_EX_REDIRECT_EXMEM_LOAD_FORWARD=1
set ENABLE_ID_BRANCH_FOLD=0
set ENABLE_ID_BRANCH_FOLD_NEXT_CACHE=1
set ENABLE_EX_REDIRECT_FOLD=1
set ENABLE_ID_BRANCH_NT_NEXT_CACHE=1
set ENABLE_ID_BRANCH_NOT_TAKEN_LOAD_FOLD=0
set ENABLE_ID_ALU_PAIR_FOLD=0
set ENABLE_ID_ALU_DEP_FOLD=0
set ENABLE_REDIRECT_TARGET_CACHE=1
set ENABLE_REDIRECT_CACHE_REGULAR_LOOKUP=1
set ENABLE_REDIRECT_CACHE_REGULAR_SIMPLE_LOOKUP=0
set ENABLE_REDIRECT_CACHE_EX_SIMPLE_BLOCK=0
set ENABLE_FETCH_REDIRECT_REUSE=0
set ENABLE_FETCH_LIVE_BYPASS=1
set ENABLE_FETCH_REDIRECT_SAME_CYCLE_REQ=1
set ENABLE_REDIRECT_CACHE_HIT_EXTRA_IMEM_REQ=0
set ENABLE_REDIRECT_CACHE_PC_SKIP=1
set ENABLE_IF_ID_PAYLOAD_SIMPLE_CE=0
set REDIRECT_CACHE_ENTRIES=1024
set REDIRECT_CACHE_XOR_INDEX=0
set ENABLE_DYNAMIC_BRANCH_PREDICT=0
set BRANCH_BHT_ENTRIES=64
set BRANCH_STATIC_PREDICT_MODE=0
set BRANCH_BHT_STRONG_ONLY=0
set DMEM_NEGEDGE_READ=0
set DMEM_READ_PREISSUE=0
set DCACHE_EN=0
set DCACHE_SIZE_BYTES=4096
set ENABLE_DCACHE_LOAD_USE_SPEC=0
set ENABLE_CONTROL_REDIRECT_DCACHE_LOAD_USE_SPEC=1
set ENABLE_BRANCH_REDIRECT_DCACHE_LOAD_USE_SPEC=1
set ENABLE_JALR_REDIRECT_DCACHE_LOAD_USE_SPEC=1
set ENABLE_FRONTEND_DCACHE_LOAD_USE_SPEC=1
set ENABLE_FOLD_DCACHE_LOAD_USE_SPEC=1
set ENABLE_FOLD_EXMEM_LOAD_USE_SPEC=1
set ENABLE_EXMEM_LOAD_MUL_FORWARD=1
set ENABLE_DCACHE_NEXT_PREFETCH=0
set ENABLE_DCACHE_WORD_ONLY=0
set ICACHE_EN=0
set RAM_BYTES=65536

echo %TARGET% | findstr /I "rv32i_zmmul" >nul
if not errorlevel 1 (
    set ENABLE_M_EXTENSION=0
    set ENABLE_ZMMUL_EXTENSION=1
)
echo %TARGET% | findstr /I "zba zbb zbs bitmanip" >nul
if not errorlevel 1 set ENABLE_BITMANIP_EXTENSION=1
echo %TARGET% | findstr /I "zbc" >nul
if not errorlevel 1 set ENABLE_ZBC_EXTENSION=1
echo %TARGET% | findstr /I "zicond" >nul
if not errorlevel 1 set ENABLE_ZICOND_EXTENSION=1
echo %TARGET% | findstr /I "zbkb" >nul
if not errorlevel 1 set ENABLE_ZBKB_EXTENSION=1
echo %TARGET% | findstr /I "xthead" >nul
if not errorlevel 1 (
    set ENABLE_XTHEAD_EXTENSION=1
    set ENABLE_XTHEAD_COND_MOVE=1
)
echo %TARGET% | findstr /I "nomac noxtmac" >nul
if not errorlevel 1 set ENABLE_XTHEAD_MUL_EXTENSION=0
echo %TARGET% | findstr /I "nocondmov" >nul
if not errorlevel 1 set ENABLE_XTHEAD_COND_MOVE=0
echo %TARGET% | findstr /I "noaddsl" >nul
if not errorlevel 1 set ENABLE_XTHEAD_ADDSL_EXTENSION=0
echo %TARGET% | findstr /I "nomempair" >nul
if not errorlevel 1 set ENABLE_XTHEAD_MEMPAIR_EXTENSION=0
echo %TARGET% | findstr /I "nobaseupd" >nul
if not errorlevel 1 set ENABLE_XTHEAD_BASE_UPDATE_EXTENSION=0
echo %TARGET% | findstr /I "noidbr" >nul
if not errorlevel 1 set ENABLE_ID_BRANCH_EX_FORWARD=0

if not "%YH_DHRYSTONE_FPGA_ENABLE_M_EXTENSION%"=="" set ENABLE_M_EXTENSION=%YH_DHRYSTONE_FPGA_ENABLE_M_EXTENSION%
if not "%YH_DHRYSTONE_FPGA_ENABLE_ZMMUL_EXTENSION%"=="" set ENABLE_ZMMUL_EXTENSION=%YH_DHRYSTONE_FPGA_ENABLE_ZMMUL_EXTENSION%
if not "%YH_DHRYSTONE_FPGA_ENABLE_BITMANIP_EXTENSION%"=="" set ENABLE_BITMANIP_EXTENSION=%YH_DHRYSTONE_FPGA_ENABLE_BITMANIP_EXTENSION%
if not "%YH_DHRYSTONE_FPGA_ENABLE_ZBC_EXTENSION%"=="" set ENABLE_ZBC_EXTENSION=%YH_DHRYSTONE_FPGA_ENABLE_ZBC_EXTENSION%
if not "%YH_DHRYSTONE_FPGA_ENABLE_ZICOND_EXTENSION%"=="" set ENABLE_ZICOND_EXTENSION=%YH_DHRYSTONE_FPGA_ENABLE_ZICOND_EXTENSION%
if not "%YH_DHRYSTONE_FPGA_ENABLE_ZBKB_EXTENSION%"=="" set ENABLE_ZBKB_EXTENSION=%YH_DHRYSTONE_FPGA_ENABLE_ZBKB_EXTENSION%
if not "%YH_DHRYSTONE_FPGA_ENABLE_XTHEAD_EXTENSION%"=="" set ENABLE_XTHEAD_EXTENSION=%YH_DHRYSTONE_FPGA_ENABLE_XTHEAD_EXTENSION%
if not "%YH_DHRYSTONE_FPGA_ENABLE_XTHEAD_CRC_EXTENSION%"=="" set ENABLE_XTHEAD_CRC_EXTENSION=%YH_DHRYSTONE_FPGA_ENABLE_XTHEAD_CRC_EXTENSION%
if not "%YH_DHRYSTONE_FPGA_ENABLE_XTHEAD_MUL_EXTENSION%"=="" set ENABLE_XTHEAD_MUL_EXTENSION=%YH_DHRYSTONE_FPGA_ENABLE_XTHEAD_MUL_EXTENSION%
if not "%YH_DHRYSTONE_FPGA_ENABLE_XTHEAD_COND_MOVE%"=="" set ENABLE_XTHEAD_COND_MOVE=%YH_DHRYSTONE_FPGA_ENABLE_XTHEAD_COND_MOVE%
if not "%YH_DHRYSTONE_FPGA_ENABLE_XTHEAD_ADDSL_EXTENSION%"=="" set ENABLE_XTHEAD_ADDSL_EXTENSION=%YH_DHRYSTONE_FPGA_ENABLE_XTHEAD_ADDSL_EXTENSION%
if not "%YH_DHRYSTONE_FPGA_ENABLE_XTHEAD_MEMPAIR_EXTENSION%"=="" set ENABLE_XTHEAD_MEMPAIR_EXTENSION=%YH_DHRYSTONE_FPGA_ENABLE_XTHEAD_MEMPAIR_EXTENSION%
if not "%YH_DHRYSTONE_FPGA_ENABLE_XTHEAD_BASE_UPDATE_EXTENSION%"=="" set ENABLE_XTHEAD_BASE_UPDATE_EXTENSION=%YH_DHRYSTONE_FPGA_ENABLE_XTHEAD_BASE_UPDATE_EXTENSION%
if not "%YH_DHRYSTONE_FPGA_ID_BRANCH_EX_FORWARD%"=="" set ENABLE_ID_BRANCH_EX_FORWARD=%YH_DHRYSTONE_FPGA_ID_BRANCH_EX_FORWARD%
if not "%YH_DHRYSTONE_FPGA_ID_BRANCH_EXMEM_LOAD_FORWARD%"=="" set ENABLE_ID_BRANCH_EXMEM_LOAD_FORWARD=%YH_DHRYSTONE_FPGA_ID_BRANCH_EXMEM_LOAD_FORWARD%
if not "%YH_DHRYSTONE_FPGA_EX_REDIRECT_EXMEM_LOAD_FORWARD%"=="" set ENABLE_EX_REDIRECT_EXMEM_LOAD_FORWARD=%YH_DHRYSTONE_FPGA_EX_REDIRECT_EXMEM_LOAD_FORWARD%
if not "%YH_DHRYSTONE_FPGA_ID_BRANCH_FOLD%"=="" set ENABLE_ID_BRANCH_FOLD=%YH_DHRYSTONE_FPGA_ID_BRANCH_FOLD%
if not "%YH_DHRYSTONE_FPGA_ID_BRANCH_FOLD_NEXT_CACHE%"=="" set ENABLE_ID_BRANCH_FOLD_NEXT_CACHE=%YH_DHRYSTONE_FPGA_ID_BRANCH_FOLD_NEXT_CACHE%
if not "%YH_DHRYSTONE_FPGA_EX_REDIRECT_FOLD%"=="" set ENABLE_EX_REDIRECT_FOLD=%YH_DHRYSTONE_FPGA_EX_REDIRECT_FOLD%
if not "%YH_DHRYSTONE_FPGA_ID_BRANCH_NT_NEXT_CACHE%"=="" set ENABLE_ID_BRANCH_NT_NEXT_CACHE=%YH_DHRYSTONE_FPGA_ID_BRANCH_NT_NEXT_CACHE%
if not "%YH_DHRYSTONE_FPGA_ID_BRANCH_NOT_TAKEN_LOAD_FOLD%"=="" set ENABLE_ID_BRANCH_NOT_TAKEN_LOAD_FOLD=%YH_DHRYSTONE_FPGA_ID_BRANCH_NOT_TAKEN_LOAD_FOLD%
if not "%YH_DHRYSTONE_FPGA_ID_ALU_PAIR_FOLD%"=="" set ENABLE_ID_ALU_PAIR_FOLD=%YH_DHRYSTONE_FPGA_ID_ALU_PAIR_FOLD%
if not "%YH_DHRYSTONE_FPGA_ID_ALU_DEP_FOLD%"=="" set ENABLE_ID_ALU_DEP_FOLD=%YH_DHRYSTONE_FPGA_ID_ALU_DEP_FOLD%
if not "%YH_DHRYSTONE_FPGA_REDIRECT_TARGET_CACHE%"=="" set ENABLE_REDIRECT_TARGET_CACHE=%YH_DHRYSTONE_FPGA_REDIRECT_TARGET_CACHE%
if not "%YH_DHRYSTONE_FPGA_REDIRECT_CACHE_REGULAR_LOOKUP%"=="" set ENABLE_REDIRECT_CACHE_REGULAR_LOOKUP=%YH_DHRYSTONE_FPGA_REDIRECT_CACHE_REGULAR_LOOKUP%
if not "%YH_DHRYSTONE_FPGA_REDIRECT_CACHE_REGULAR_SIMPLE_LOOKUP%"=="" set ENABLE_REDIRECT_CACHE_REGULAR_SIMPLE_LOOKUP=%YH_DHRYSTONE_FPGA_REDIRECT_CACHE_REGULAR_SIMPLE_LOOKUP%
if not "%YH_DHRYSTONE_FPGA_REDIRECT_CACHE_EX_SIMPLE_BLOCK%"=="" set ENABLE_REDIRECT_CACHE_EX_SIMPLE_BLOCK=%YH_DHRYSTONE_FPGA_REDIRECT_CACHE_EX_SIMPLE_BLOCK%
if not "%YH_DHRYSTONE_FPGA_FETCH_REDIRECT_REUSE%"=="" set ENABLE_FETCH_REDIRECT_REUSE=%YH_DHRYSTONE_FPGA_FETCH_REDIRECT_REUSE%
if not "%YH_DHRYSTONE_FPGA_FETCH_LIVE_BYPASS%"=="" set ENABLE_FETCH_LIVE_BYPASS=%YH_DHRYSTONE_FPGA_FETCH_LIVE_BYPASS%
if not "%YH_DHRYSTONE_FPGA_FETCH_REDIRECT_SAME_CYCLE_REQ%"=="" set ENABLE_FETCH_REDIRECT_SAME_CYCLE_REQ=%YH_DHRYSTONE_FPGA_FETCH_REDIRECT_SAME_CYCLE_REQ%
if not "%YH_DHRYSTONE_FPGA_REDIRECT_CACHE_HIT_EXTRA_IMEM_REQ%"=="" set ENABLE_REDIRECT_CACHE_HIT_EXTRA_IMEM_REQ=%YH_DHRYSTONE_FPGA_REDIRECT_CACHE_HIT_EXTRA_IMEM_REQ%
if not "%YH_DHRYSTONE_FPGA_REDIRECT_CACHE_PC_SKIP%"=="" set ENABLE_REDIRECT_CACHE_PC_SKIP=%YH_DHRYSTONE_FPGA_REDIRECT_CACHE_PC_SKIP%
if not "%YH_DHRYSTONE_FPGA_IF_ID_PAYLOAD_SIMPLE_CE%"=="" set ENABLE_IF_ID_PAYLOAD_SIMPLE_CE=%YH_DHRYSTONE_FPGA_IF_ID_PAYLOAD_SIMPLE_CE%
if not "%YH_DHRYSTONE_FPGA_REDIRECT_CACHE_ENTRIES%"=="" set REDIRECT_CACHE_ENTRIES=%YH_DHRYSTONE_FPGA_REDIRECT_CACHE_ENTRIES%
if not "%YH_DHRYSTONE_FPGA_REDIRECT_CACHE_XOR_INDEX%"=="" set REDIRECT_CACHE_XOR_INDEX=%YH_DHRYSTONE_FPGA_REDIRECT_CACHE_XOR_INDEX%
if not "%YH_DHRYSTONE_FPGA_DYNAMIC_BRANCH_PREDICT%"=="" set ENABLE_DYNAMIC_BRANCH_PREDICT=%YH_DHRYSTONE_FPGA_DYNAMIC_BRANCH_PREDICT%
if not "%YH_DHRYSTONE_FPGA_BRANCH_BHT_ENTRIES%"=="" set BRANCH_BHT_ENTRIES=%YH_DHRYSTONE_FPGA_BRANCH_BHT_ENTRIES%
if not "%YH_DHRYSTONE_FPGA_BRANCH_STATIC_PREDICT_MODE%"=="" set BRANCH_STATIC_PREDICT_MODE=%YH_DHRYSTONE_FPGA_BRANCH_STATIC_PREDICT_MODE%
if not "%YH_DHRYSTONE_FPGA_BRANCH_BHT_STRONG_ONLY%"=="" set BRANCH_BHT_STRONG_ONLY=%YH_DHRYSTONE_FPGA_BRANCH_BHT_STRONG_ONLY%
if not "%YH_DHRYSTONE_FPGA_DMEM_NEGEDGE_READ%"=="" set DMEM_NEGEDGE_READ=%YH_DHRYSTONE_FPGA_DMEM_NEGEDGE_READ%
if not "%YH_DHRYSTONE_FPGA_DMEM_READ_PREISSUE%"=="" set DMEM_READ_PREISSUE=%YH_DHRYSTONE_FPGA_DMEM_READ_PREISSUE%
if not "%YH_DHRYSTONE_FPGA_DCACHE_EN%"=="" set DCACHE_EN=%YH_DHRYSTONE_FPGA_DCACHE_EN%
if not "%YH_DHRYSTONE_FPGA_DCACHE_SIZE_BYTES%"=="" set DCACHE_SIZE_BYTES=%YH_DHRYSTONE_FPGA_DCACHE_SIZE_BYTES%
if not "%YH_DHRYSTONE_FPGA_DCACHE_LOAD_USE_SPEC%"=="" set ENABLE_DCACHE_LOAD_USE_SPEC=%YH_DHRYSTONE_FPGA_DCACHE_LOAD_USE_SPEC%
if not "%YH_DHRYSTONE_FPGA_CONTROL_REDIRECT_DCACHE_LOAD_USE_SPEC%"=="" set ENABLE_CONTROL_REDIRECT_DCACHE_LOAD_USE_SPEC=%YH_DHRYSTONE_FPGA_CONTROL_REDIRECT_DCACHE_LOAD_USE_SPEC%
if not "%YH_DHRYSTONE_FPGA_BRANCH_REDIRECT_DCACHE_LOAD_USE_SPEC%"=="" set ENABLE_BRANCH_REDIRECT_DCACHE_LOAD_USE_SPEC=%YH_DHRYSTONE_FPGA_BRANCH_REDIRECT_DCACHE_LOAD_USE_SPEC%
if not "%YH_DHRYSTONE_FPGA_JALR_REDIRECT_DCACHE_LOAD_USE_SPEC%"=="" set ENABLE_JALR_REDIRECT_DCACHE_LOAD_USE_SPEC=%YH_DHRYSTONE_FPGA_JALR_REDIRECT_DCACHE_LOAD_USE_SPEC%
if not "%YH_DHRYSTONE_FPGA_FRONTEND_DCACHE_LOAD_USE_SPEC%"=="" set ENABLE_FRONTEND_DCACHE_LOAD_USE_SPEC=%YH_DHRYSTONE_FPGA_FRONTEND_DCACHE_LOAD_USE_SPEC%
if not "%YH_DHRYSTONE_FPGA_FOLD_DCACHE_LOAD_USE_SPEC%"=="" set ENABLE_FOLD_DCACHE_LOAD_USE_SPEC=%YH_DHRYSTONE_FPGA_FOLD_DCACHE_LOAD_USE_SPEC%
if not "%YH_DHRYSTONE_FPGA_FOLD_EXMEM_LOAD_USE_SPEC%"=="" set ENABLE_FOLD_EXMEM_LOAD_USE_SPEC=%YH_DHRYSTONE_FPGA_FOLD_EXMEM_LOAD_USE_SPEC%
if not "%YH_DHRYSTONE_FPGA_EXMEM_LOAD_MUL_FORWARD%"=="" set ENABLE_EXMEM_LOAD_MUL_FORWARD=%YH_DHRYSTONE_FPGA_EXMEM_LOAD_MUL_FORWARD%
if not "%YH_DHRYSTONE_FPGA_DCACHE_NEXT_PREFETCH%"=="" set ENABLE_DCACHE_NEXT_PREFETCH=%YH_DHRYSTONE_FPGA_DCACHE_NEXT_PREFETCH%
if not "%YH_DHRYSTONE_FPGA_DCACHE_WORD_ONLY%"=="" set ENABLE_DCACHE_WORD_ONLY=%YH_DHRYSTONE_FPGA_DCACHE_WORD_ONLY%
if not "%YH_DHRYSTONE_FPGA_ICACHE_EN%"=="" set ICACHE_EN=%YH_DHRYSTONE_FPGA_ICACHE_EN%
if not "%YH_DHRYSTONE_FPGA_RAM_BYTES%"=="" set RAM_BYTES=%YH_DHRYSTONE_FPGA_RAM_BYTES%

echo Dhrystone FPGA target: %TARGET%
echo Dhrystone FPGA hw: dcache=%DCACHE_EN% dcache_bytes=%DCACHE_SIZE_BYTES% rc_entries=%REDIRECT_CACHE_ENTRIES% dmem_negedge=%DMEM_NEGEDGE_READ% dmem_preissue=%DMEM_READ_PREISSUE%

call "%~dp0build_dhrystone.bat" %OUTPUT_NAME% %DHRYSTONE_RUNS% %TARGET%
if errorlevel 1 exit /b 1

set XVLOG=
set XELAB=
set XSIM=
set PYTHON_CMD=
set XSIM_RUN_DIR=

for %%T in (xvlog.bat xvlog) do (
    where %%T >nul 2>nul
    if not errorlevel 1 (
        set XVLOG=%%T
        goto :xvlog_done
    )
)
:xvlog_done

for %%T in (xelab.bat xelab) do (
    where %%T >nul 2>nul
    if not errorlevel 1 (
        set XELAB=%%T
        goto :xelab_done
    )
)
:xelab_done

for %%T in (xsim.bat xsim) do (
    where %%T >nul 2>nul
    if not errorlevel 1 (
        set XSIM=%%T
        goto :xsim_done
    )
)
:xsim_done

if not defined XVLOG (
    echo Missing xvlog.
    exit /b 1
)
if not defined XELAB (
    echo Missing xelab.
    exit /b 1
)
if not defined XSIM (
    echo Missing xsim.
    exit /b 1
)

call "%~dp0resolve_python.bat" PYTHON_CMD
if not defined PYTHON_CMD (
    echo Missing Python.
    exit /b 1
)

call "%~dp0prepare_xsim_runtime.bat" dhrystone_fpga XSIM_RUN_DIR
if not defined XSIM_RUN_DIR exit /b 1

if not exist "%XSIM_RUN_DIR%\build\sw" mkdir "%XSIM_RUN_DIR%\build\sw"
copy /y "%PROJECT_DIR%\build\sw\%OUTPUT_NAME%.hex" "%XSIM_RUN_DIR%\build\sw\YH_rv_cpu_dhrystone.hex" >nul
if errorlevel 1 exit /b 1

pushd "%XSIM_RUN_DIR%"

call %XVLOG% --sv -i "%PROJECT_DIR%\rtl" ^
    "%PROJECT_DIR%\tb\YH_rv_cpu_dhrystone_tb.v" ^
    "%PROJECT_DIR%\rtl\YH_rv_cpu_soc.v" ^
    "%PROJECT_DIR%\rtl\YH_rv_sync_imem_rom.v" ^
    "%PROJECT_DIR%\rtl\YH_rv_sync_rom32.v" ^
    "%PROJECT_DIR%\rtl\YH_rv_dmem_ram.v" ^
    "%PROJECT_DIR%\rtl\YH_rv_cpu_dcache.v" ^
    "%PROJECT_DIR%\rtl\YH_rv_cpu_icache.v" ^
    "%PROJECT_DIR%\rtl\YH_rv_cpu.v" ^
    "%PROJECT_DIR%\rtl\YH_rv_cpu_if_stage.v" ^
    "%PROJECT_DIR%\rtl\YH_rv_cpu_id_stage.v" ^
    "%PROJECT_DIR%\rtl\YH_rv_cpu_ex_stage.v" ^
    "%PROJECT_DIR%\rtl\YH_rv_cpu_mem_stage.v" ^
    "%PROJECT_DIR%\rtl\YH_rv_cpu_wb_stage.v" ^
    "%PROJECT_DIR%\rtl\YH_rv_cpu_hazard_unit.v" ^
    "%PROJECT_DIR%\rtl\YH_rv_cpu_decoder.v" ^
    "%PROJECT_DIR%\rtl\YH_rv_cpu_regfile.v" ^
    "%PROJECT_DIR%\rtl\YH_rv_cpu_alu.v"
if errorlevel 1 goto :fail

call %XELAB% %TEST_TOP% ^
    -generic_top "ENABLE_M_EXTENSION=%ENABLE_M_EXTENSION%" ^
    -generic_top "ENABLE_ZMMUL_EXTENSION=%ENABLE_ZMMUL_EXTENSION%" ^
    -generic_top "ENABLE_BITMANIP_EXTENSION=%ENABLE_BITMANIP_EXTENSION%" ^
    -generic_top "ENABLE_ZBC_EXTENSION=%ENABLE_ZBC_EXTENSION%" ^
    -generic_top "ENABLE_ZICOND_EXTENSION=%ENABLE_ZICOND_EXTENSION%" ^
    -generic_top "ENABLE_ZBKB_EXTENSION=%ENABLE_ZBKB_EXTENSION%" ^
    -generic_top "ENABLE_XTHEAD_EXTENSION=%ENABLE_XTHEAD_EXTENSION%" ^
    -generic_top "ENABLE_XTHEAD_CRC_EXTENSION=%ENABLE_XTHEAD_CRC_EXTENSION%" ^
    -generic_top "ENABLE_XTHEAD_MUL_EXTENSION=%ENABLE_XTHEAD_MUL_EXTENSION%" ^
    -generic_top "ENABLE_XTHEAD_COND_MOVE=%ENABLE_XTHEAD_COND_MOVE%" ^
    -generic_top "ENABLE_XTHEAD_ADDSL_EXTENSION=%ENABLE_XTHEAD_ADDSL_EXTENSION%" ^
    -generic_top "ENABLE_XTHEAD_MEMPAIR_EXTENSION=%ENABLE_XTHEAD_MEMPAIR_EXTENSION%" ^
    -generic_top "ENABLE_XTHEAD_BASE_UPDATE_EXTENSION=%ENABLE_XTHEAD_BASE_UPDATE_EXTENSION%" ^
    -generic_top "ENABLE_ID_BRANCH_EX_FORWARD=%ENABLE_ID_BRANCH_EX_FORWARD%" ^
    -generic_top "ENABLE_ID_BRANCH_EXMEM_LOAD_FORWARD=%ENABLE_ID_BRANCH_EXMEM_LOAD_FORWARD%" ^
    -generic_top "ENABLE_EX_REDIRECT_EXMEM_LOAD_FORWARD=%ENABLE_EX_REDIRECT_EXMEM_LOAD_FORWARD%" ^
    -generic_top "ENABLE_ID_BRANCH_FOLD=%ENABLE_ID_BRANCH_FOLD%" ^
    -generic_top "ENABLE_ID_BRANCH_FOLD_NEXT_CACHE=%ENABLE_ID_BRANCH_FOLD_NEXT_CACHE%" ^
    -generic_top "ENABLE_EX_REDIRECT_FOLD=%ENABLE_EX_REDIRECT_FOLD%" ^
    -generic_top "ENABLE_ID_BRANCH_NT_NEXT_CACHE=%ENABLE_ID_BRANCH_NT_NEXT_CACHE%" ^
    -generic_top "ENABLE_ID_BRANCH_NOT_TAKEN_LOAD_FOLD=%ENABLE_ID_BRANCH_NOT_TAKEN_LOAD_FOLD%" ^
    -generic_top "ENABLE_ID_ALU_PAIR_FOLD=%ENABLE_ID_ALU_PAIR_FOLD%" ^
    -generic_top "ENABLE_ID_ALU_DEP_FOLD=%ENABLE_ID_ALU_DEP_FOLD%" ^
    -generic_top "ENABLE_REDIRECT_TARGET_CACHE=%ENABLE_REDIRECT_TARGET_CACHE%" ^
    -generic_top "ENABLE_REDIRECT_CACHE_REGULAR_LOOKUP=%ENABLE_REDIRECT_CACHE_REGULAR_LOOKUP%" ^
    -generic_top "ENABLE_REDIRECT_CACHE_REGULAR_SIMPLE_LOOKUP=%ENABLE_REDIRECT_CACHE_REGULAR_SIMPLE_LOOKUP%" ^
    -generic_top "ENABLE_REDIRECT_CACHE_EX_SIMPLE_BLOCK=%ENABLE_REDIRECT_CACHE_EX_SIMPLE_BLOCK%" ^
    -generic_top "ENABLE_FETCH_REDIRECT_REUSE=%ENABLE_FETCH_REDIRECT_REUSE%" ^
    -generic_top "ENABLE_FETCH_LIVE_BYPASS=%ENABLE_FETCH_LIVE_BYPASS%" ^
    -generic_top "ENABLE_FETCH_REDIRECT_SAME_CYCLE_REQ=%ENABLE_FETCH_REDIRECT_SAME_CYCLE_REQ%" ^
    -generic_top "ENABLE_REDIRECT_CACHE_HIT_EXTRA_IMEM_REQ=%ENABLE_REDIRECT_CACHE_HIT_EXTRA_IMEM_REQ%" ^
    -generic_top "ENABLE_REDIRECT_CACHE_PC_SKIP=%ENABLE_REDIRECT_CACHE_PC_SKIP%" ^
    -generic_top "ENABLE_IF_ID_PAYLOAD_SIMPLE_CE=%ENABLE_IF_ID_PAYLOAD_SIMPLE_CE%" ^
    -generic_top "REDIRECT_CACHE_ENTRIES=%REDIRECT_CACHE_ENTRIES%" ^
    -generic_top "REDIRECT_CACHE_XOR_INDEX=%REDIRECT_CACHE_XOR_INDEX%" ^
    -generic_top "ENABLE_DYNAMIC_BRANCH_PREDICT=%ENABLE_DYNAMIC_BRANCH_PREDICT%" ^
    -generic_top "BRANCH_BHT_ENTRIES=%BRANCH_BHT_ENTRIES%" ^
    -generic_top "BRANCH_STATIC_PREDICT_MODE=%BRANCH_STATIC_PREDICT_MODE%" ^
    -generic_top "BRANCH_BHT_STRONG_ONLY=%BRANCH_BHT_STRONG_ONLY%" ^
    -generic_top "DMEM_NEGEDGE_READ=%DMEM_NEGEDGE_READ%" ^
    -generic_top "DMEM_READ_PREISSUE=%DMEM_READ_PREISSUE%" ^
    -generic_top "DCACHE_EN=%DCACHE_EN%" ^
    -generic_top "DCACHE_SIZE_BYTES=%DCACHE_SIZE_BYTES%" ^
    -generic_top "ENABLE_DCACHE_LOAD_USE_SPEC=%ENABLE_DCACHE_LOAD_USE_SPEC%" ^
    -generic_top "ENABLE_CONTROL_REDIRECT_DCACHE_LOAD_USE_SPEC=%ENABLE_CONTROL_REDIRECT_DCACHE_LOAD_USE_SPEC%" ^
    -generic_top "ENABLE_BRANCH_REDIRECT_DCACHE_LOAD_USE_SPEC=%ENABLE_BRANCH_REDIRECT_DCACHE_LOAD_USE_SPEC%" ^
    -generic_top "ENABLE_JALR_REDIRECT_DCACHE_LOAD_USE_SPEC=%ENABLE_JALR_REDIRECT_DCACHE_LOAD_USE_SPEC%" ^
    -generic_top "ENABLE_FRONTEND_DCACHE_LOAD_USE_SPEC=%ENABLE_FRONTEND_DCACHE_LOAD_USE_SPEC%" ^
    -generic_top "ENABLE_FOLD_DCACHE_LOAD_USE_SPEC=%ENABLE_FOLD_DCACHE_LOAD_USE_SPEC%" ^
    -generic_top "ENABLE_FOLD_EXMEM_LOAD_USE_SPEC=%ENABLE_FOLD_EXMEM_LOAD_USE_SPEC%" ^
    -generic_top "ENABLE_EXMEM_LOAD_MUL_FORWARD=%ENABLE_EXMEM_LOAD_MUL_FORWARD%" ^
    -generic_top "ENABLE_DCACHE_NEXT_PREFETCH=%ENABLE_DCACHE_NEXT_PREFETCH%" ^
    -generic_top "ENABLE_DCACHE_WORD_ONLY=%ENABLE_DCACHE_WORD_ONLY%" ^
    -generic_top "ICACHE_EN=%ICACHE_EN%" ^
    -generic_top "RAM_BYTES=%RAM_BYTES%" ^
    -s %TEST_TOP%_snapshot
if errorlevel 1 goto :fail

call %XSIM% %TEST_TOP%_snapshot -testplusarg "max_cycles=%MAX_CYCLES%" -testplusarg "dhrystone_runs=%DHRYSTONE_RUNS%" %DHRYSTONE_XSIM_EXTRA_PLUSARGS% -runall > "%LOG_FILE%" 2>&1
type "%LOG_FILE%"

findstr /c:"PASS: dhrystone completed" "%LOG_FILE%" >nul
if errorlevel 1 goto :fail

call %PYTHON_CMD% "%~dp0report_dhrystone_result.py" "%LOG_FILE%" "%CLOCK_HZ%" "%SUMMARY_FILE%"
if errorlevel 1 goto :fail

echo.
echo Dhrystone FPGA summary:
type "%SUMMARY_FILE%"

set RUN_STATUS=0
goto :done

:fail
set RUN_STATUS=%ERRORLEVEL%
if "%RUN_STATUS%"=="0" set RUN_STATUS=1

:done
popd
exit /b %RUN_STATUS%
