@echo off
setlocal EnableDelayedExpansion

set SCRIPT_DIR=%~dp0
for %%I in ("%SCRIPT_DIR%..") do set PROJECT_DIR=%%~fI
set OUT_ROOT=%~1
set ITERATIONS=%~2
set MAX_CYCLES=%~3

if "%OUT_ROOT%"=="" set OUT_ROOT=%PROJECT_DIR%\..\artifacts\strict_50m_timing_opt_20260609\fast_matrix
if "%ITERATIONS%"=="" set ITERATIONS=1
if "%MAX_CYCLES%"=="" set MAX_CYCLES=1500000
for %%I in ("%OUT_ROOT%") do set OUT_ROOT=%%~fI
if not exist "%OUT_ROOT%" mkdir "%OUT_ROOT%"

set MATRIX_SUMMARY=%OUT_ROOT%\MATRIX_SUMMARY.md
(
  echo # Strict 50MHz Fast Matrix
  echo.
  echo Generated by `%~nx0`.
  echo.
  echo Command: `%~nx0 "%OUT_ROOT%" %ITERATIONS% %MAX_CYCLES%`
  echo.
  echo ^| Candidate ^| Result ^| CoreMark/MHz ^| Completion cycles ^| Notes ^|
  echo ^|---^|---: ^|---: ^|---: ^|---^|
) > "%MATRIX_SUMMARY%"

echo === Strict 50MHz fast matrix ===
echo out_root=%OUT_ROOT%
echo iterations=%ITERATIONS%
echo max_cycles=%MAX_CYCLES%

call :run_candidate fast_default "baseline fast-gate calibration"
call :run_candidate foldexmem0 "YH_COREMARK_FPGA_FOLD_EXMEM_LOAD_USE_SPEC=0" YH_COREMARK_FPGA_FOLD_EXMEM_LOAD_USE_SPEC 0
call :run_candidate ntnext0_foldexmem0 "YH_COREMARK_FPGA_ID_BRANCH_NT_NEXT_CACHE=0; YH_COREMARK_FPGA_FOLD_EXMEM_LOAD_USE_SPEC=0" YH_COREMARK_FPGA_ID_BRANCH_NT_NEXT_CACHE 0 YH_COREMARK_FPGA_FOLD_EXMEM_LOAD_USE_SPEC 0
call :run_candidate reglookup0 "YH_COREMARK_FPGA_REDIRECT_CACHE_REGULAR_LOOKUP=0" YH_COREMARK_FPGA_REDIRECT_CACHE_REGULAR_LOOKUP 0
call :run_candidate foldnext0 "YH_COREMARK_FPGA_ID_BRANCH_FOLD_NEXT_CACHE=0" YH_COREMARK_FPGA_ID_BRANCH_FOLD_NEXT_CACHE 0
call :run_candidate pcskip0 "YH_COREMARK_FPGA_REDIRECT_CACHE_PC_SKIP=0" YH_COREMARK_FPGA_REDIRECT_CACHE_PC_SKIP 0

echo.
echo Matrix summary: %MATRIX_SUMMARY%
exit /b 0

:run_candidate
set CANDIDATE=%~1
set NOTES=%~2
set OUT_DIR=%OUT_ROOT%\%CANDIDATE%
if not exist "%OUT_DIR%" mkdir "%OUT_DIR%"

echo.
echo === Candidate: %CANDIDATE% ===
setlocal
shift
shift
:set_env_loop
if "%~1"=="" goto env_done
set "%~1=%~2"
shift
shift
goto set_env_loop
:env_done

call "%SCRIPT_DIR%run_coremark50_fast_gate.bat" "%OUT_DIR%" %ITERATIONS% %MAX_CYCLES%
set RC=%ERRORLEVEL%
set SUMMARY=%OUT_DIR%\coremark50_fast_gate_iter%ITERATIONS%.summary.txt
set COREMARK=NA
set CYCLES=NA
if exist "%SUMMARY%" (
  for /f "tokens=2 delims==" %%A in ('findstr /b "coremark_per_mhz=" "%SUMMARY%"') do set COREMARK=%%A
  for /f "tokens=2 delims==" %%A in ('findstr /b "completion_cycles=" "%SUMMARY%"') do set CYCLES=%%A
)
if "%RC%"=="0" (
  set RESULT=PASS
) else (
  set RESULT=FAIL_%RC%
)
endlocal & set RESULT=%RESULT%& set COREMARK=%COREMARK%& set CYCLES=%CYCLES%
echo ^| %CANDIDATE% ^| %RESULT% ^| %COREMARK% ^| %CYCLES% ^| %NOTES% ^| >> "%MATRIX_SUMMARY%"
echo result=%RESULT% coremark_per_mhz=%COREMARK% completion_cycles=%CYCLES%
exit /b 0
