`timescale 1ns / 1ps

module YH_rv_cpu_dhrystone_rv32_zmmul_zbc_zicond_xthead_mac_tagtrim_idbr_tb;

localparam string ROM_HEX = "build/sw/YH_rv_cpu_dhrystone.hex";

YH_rv_cpu_dhrystone_tb #(
    .ROM_HEX(ROM_HEX),
    .ENABLE_M_EXTENSION(0),
    .ENABLE_ZMMUL_EXTENSION(1),
    .ENABLE_BITMANIP_EXTENSION(1),
    .ENABLE_ZBC_EXTENSION(1),
    .ENABLE_ZICOND_EXTENSION(1),
    .ENABLE_ZBKB_EXTENSION(0),
    .ENABLE_XTHEAD_EXTENSION(1),
    .ENABLE_XTHEAD_CRC_EXTENSION(1),
    .ENABLE_XTHEAD_MUL_EXTENSION(1),
    .ENABLE_XTHEAD_COND_MOVE(1),
    .ENABLE_XTHEAD_MEMPAIR_EXTENSION(1),
    .ENABLE_XTHEAD_BASE_UPDATE_EXTENSION(1),
    .ENABLE_ID_BRANCH_EX_FORWARD(1),
    .ENABLE_ID_BRANCH_FOLD(1),
    .ENABLE_ID_BRANCH_FOLD_NEXT_CACHE(1),
    .ENABLE_ID_BRANCH_NOT_TAKEN_LOAD_FOLD(1),
    .ENABLE_REDIRECT_TARGET_CACHE(1),
    .ENABLE_REDIRECT_CACHE_REGULAR_LOOKUP(1),
    .ENABLE_FETCH_REDIRECT_REUSE(0),
    .REDIRECT_CACHE_ENTRIES(128),
    .ENABLE_DYNAMIC_BRANCH_PREDICT(1),
    .BRANCH_BHT_ENTRIES(64),
    .DCACHE_EN(1),
    .DCACHE_SIZE_BYTES(256),
    .ENABLE_DCACHE_LOAD_USE_SPEC(1),
    .ENABLE_DCACHE_NEXT_PREFETCH(0),
    .ICACHE_EN(0),
    .RAM_BYTES(65536)
) uut ();

endmodule
